# Generated by Django 2.1.4 on 2019-01-01 18:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField()),
                ('email', models.CharField(max_length=75)),
                ('sex', models.CharField(max_length=50)),
                ('race', models.CharField(max_length=50)),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
