# Generated by Django 2.1.4 on 2019-01-11 22:33

from django.db import migrations
import django_measurement.models
import measurement.measures.distance
import measurement.measures.mass


class Migration(migrations.Migration):

    dependencies = [
        ('health_story', '0002_auto_20190111_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='height',
            field=django_measurement.models.MeasurementField(measurement=measurement.measures.distance.Distance, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='weight',
            field=django_measurement.models.MeasurementField(measurement=measurement.measures.mass.Mass, null=True),
        ),
    ]
