# Generated by Django 2.1.4 on 2019-01-14 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_story', '0004_healthencounter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='healthencounter',
            name='type_of_encounter',
            field=models.CharField(choices=[('surgery', 'Surgery'), ('routine physical', 'Routine Physical'), ('general illness', 'General Illness'), ('emergency room', 'Emergency Room')], max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='relatives',
            field=models.ManyToManyField(to='health_story.Relative'),
        ),
    ]
