# Generated by Django 2.1.4 on 2019-01-14 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_story', '0005_auto_20190114_0404'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='relative',
            name='diseases',
            field=models.ManyToManyField(to='health_story.Disease'),
        ),
    ]
