# Generated by Django 2.1.4 on 2019-01-20 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_story', '0006_auto_20190114_0417'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='physician_code',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='patient',
            name='physician_code_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.CharField(blank=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='patient',
            name='race',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
