# Generated by Django 2.1.4 on 2019-01-20 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_story', '0007_auto_20190120_0143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='medications',
            field=models.ManyToManyField(to='health_story.Medication'),
        ),
    ]
