# Generated by Django 2.1.4 on 2019-01-20 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_story', '0009_auto_20190120_0205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='conditions',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='medications',
        ),
        migrations.RemoveField(
            model_name='relative',
            name='diseases',
        ),
        migrations.AddField(
            model_name='healthencounter',
            name='conditions',
            field=models.ManyToManyField(to='health_story.Condition'),
        ),
        migrations.AddField(
            model_name='healthencounter',
            name='medications',
            field=models.ManyToManyField(to='health_story.Medication'),
        ),
        migrations.AddField(
            model_name='relative',
            name='conditions',
            field=models.ManyToManyField(to='health_story.Condition'),
        ),
        migrations.DeleteModel(
            name='Disease',
        ),
    ]
