# Generated by Django 2.1.4 on 2019-01-21 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_story', '0011_patient_admin_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='relative',
            name='type_of_relationship',
            field=models.CharField(blank=True, choices=[('mother', 'Mother'), ('father', 'Father'), ('brother', 'Brother'), ('sister', 'Sister'), ('paternal grandfather', 'Paternal Grandfather'), ('maternal grandfather', 'Maternal Grandfather'), ('paternal grandmother', 'Paternal Grandmother'), ('maternal grandmother', 'Maternal Grandmother')], max_length=100),
        ),
    ]
