from django.db import models
from datetime import date, datetime
from django.utils import timezone
from measurement.measures import Weight, Distance
from django_measurement.models import MeasurementField
from .helper import choices


class Patient(models.Model):
    # Demographic information
    username = models.CharField(max_length=30)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    date_of_birth = models.DateField()
    email = models.CharField(max_length=75, blank=True)
    sex = models.CharField(max_length=50, blank=True)
    race = models.CharField(max_length=50, blank=True)

    # Vital information
    weight = MeasurementField(measurement=Weight, null=True)
    height = MeasurementField(measurement=Distance, null=True)

    # The following fields are calculated without user input.
    date_created = models.DateField(default=timezone.now)

    # Family history
    relatives = models.ManyToManyField('Relative')

    # Medications
    medications = models.ManyToManyField('Medication')

    # Conditions
    conditions = models.ManyToManyField('Condition')

    # The physician code expires in a short amount of time.
    physician_code = models.CharField(max_length=30, blank=True)
    physician_code_created = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        """Returns the string representation of the patient object.

        Returns:
            string: Full name of the patient.
        """
        return self.get_full_name()

    def get_full_name(self):
        """Returns the full name of the patient.

        Returns:
            string: The full name of the patient.
        """
        return self.first_name + " " + self.last_name

    def get_age(self):
        """Calculates the age of the patient based on their date of birth.

        Returns:
            int: The age of the patient.
        """
        days_old = (date.today() - self.date_of_birth).days
        return days_old // 365

    def get_date_of_first_visit_formatted(self):
        """Formats the date of the patients first visit in a readable way.

        Returns:
            string: The date of the first visit.
        """
        return self.date_created.strftime("%b %e %Y")

    def get_date_of_birth_formatted(self):
        """Formats the date of birth of the patient.

        Returns:
            The date of the first visit in a readable format.
        """
        return self.date_of_birth.strftime("%b %e %Y")

    def get_height_formatted(self):
        """Formats the height from inches to ft inches format.

        Returns:
            A formatted string representing the patients height.
        """
        try:
            feet = int(self.height.inch) // 12
            inches = self.height.inch - float(feet * 12)
        except AttributeError:
            feet = -1
            inches = -1
        return "{feet} feet {inches} inches".format(feet=feet, inches=inches)

    def is_physician_code_valid(self, physician_code):
        """Checks if a physician code is valid to access this patients account.

        A physician code is generated by the user and expires after 1 hour (3600 seconds).
        After that time, the physician will no longer be able to access the patients
        health information.
        """
        if physician_code != self.physician_code:
            return False

        expiration_time = 3600
        time_elapsed = self.physician_code_created - datetime.now()
        if not self.physician_code_created or time_elapsed.total_seconds() > expiration_time:
            return False

        return True

    @staticmethod
    def is_user_registered(username):
        try:
            Patient.objects.get(username=username)
            return True
        except Patient.DoesNotExist:
            return False


class HealthEncounter(models.Model):
    # Parties involved.
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    # TODO Make actually object.
    physician = models.CharField(max_length=100)

    date = models.DateField(default=timezone.now)
    location = models.CharField(max_length=100)

    # TODO Make choices for this.
    type_of_encounter = models.CharField(max_length=100, choices=choices.TYPE_OF_HEALTH_ENCOUNTER)

    # TODO Make more structured.
    description = models.CharField(max_length=100)

    def __str__(self):
        """
        Returns a string representation of a HealthEncounter object.

        Returns:
             The patient name, physician name, and date.
        """
        return self.patient.get_full_name() + " with " + self.physician + " on " + self.date_formatted()

    def date_formatted(self):
        """
        Formats the date of the Health Encounter in a readable way.

        Returns:
            The date of the Health Encounter.
        """
        return self.date.strftime("%b %e %Y")

    def he_type_fa_icon(self):
        """
        Returns the fa icon name according to the health encounter type.

        Returns:
            Fa icon name.
        """
        return choices.HE_TO_ICON[self.type_of_encounter]


class Relative(models.Model):
    full_name = models.CharField(max_length=100)
    diseases = models.ManyToManyField('Disease')

    def __str__(self):
        """
        Returns a string representation of a Relative object.

        Returns:
             The relatives name.
        """
        return self.full_name


class Disease(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        """
        Returns a string representation of a Disease object.

        Returns:
             The diseases name.
        """
        return self.name


class Medication(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        """
        Returns a string representation of a Medication object.

        Returns:
             The medication's name.
        """
        return self.name


# TODO make relatives as conditions too.
class Condition(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        """
        Returns a string representation of a Condition object.

        Returns:
             The conditions's name.
        """
        return self.name
